basePath: /v1
definitions:
  models.User:
    properties:
      coordinates:
        example: 39.12355, 27.64538
        type: string
      created_at:
        example: "2021-02-24 20:19:39"
        type: string
      id:
        example: 123
        type: integer
      name:
        example: Steven
        type: string
      updated_at:
        example: "2021-02-24 20:19:39"
        type: string
    type: object
  users.MessageResponse:
    properties:
      message:
        type: string
    type: object
  users.NewUserRequest:
    properties:
      name:
        example: Paracetamol
        type: string
    required:
    - name
    type: object
host: localhost:8080
info:
  contact:
    email: kvendingoldo@gmail.com
    name: Alexander Sharov
    url: http://github.com/kvendingoldo
  description: Documentation's GU user service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GU user service
  version: "1.0"
paths:
  /users:
    get:
      description: Get all users on the system
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/users.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/users.MessageResponse'
      summary: Get all users
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create new user on the system
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.NewUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/users.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/users.MessageResponse'
      summary: Create new user
      tags:
      - user
  /users/{id}:
    delete:
      description: Delete user on the system
      parameters:
      - description: id of user
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Delete user
      tags:
      - user
    get:
      description: Get users by ID on the system
      parameters:
      - description: id of user
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/users.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/users.MessageResponse'
      summary: Get users by ID
      tags:
      - user
    put:
      description: Update user on the system
      parameters:
      - description: id of user
        in: path
        name: id
        required: true
        type: integer
      - description: User updated info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Update user
      tags:
      - user
swagger: "2.0"
